package handlers

import (
	"database/sql"
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/gin-gonic/gin"

	"open-kanban/internal/config"
	"open-kanban/internal/database"
	"open-kanban/internal/models"
)

type LoginRequest struct {
	Username string `json:"username" validate:"required,max=50"`
	Password string `json:"password" validate:"required,max=100"`
	Avatar   string `json:"avatar" validate:"omitempty,max=500"`
	Type     string `json:"type" validate:"omitempty,max=20"`
}

type AdvancedConfig struct {
	DBType         string `json:"dbType"`
	DBPath         string `json:"dbPath"`
	DBHost         string `json:"dbHost"`
	DBPort         string `json:"dbPort"`
	DBUser         string `json:"dbUser"`
	DBPassword     string `json:"dbPassword"`
	DBName         string `json:"dbName"`
	ServerPort     string `json:"serverPort"`
	AllowedOrigins string `json:"allowedOrigins"`
}

type InitRequest struct {
	Username          string         `json:"username" validate:"required,max=50"`
	Nickname          string         `json:"nickname" validate:"omitempty,max=50"`
	Password          string         `json:"password" validate:"required,max=100"`
	Avatar            string         `json:"avatar" validate:"omitempty,max=500"`
	AllowRegistration bool           `json:"allowRegistration"`
	RequirePassword   bool           `json:"requirePassword"`
	AuthEnabled       *bool          `json:"authEnabled"`
	Advanced          *AdvancedConfig `json:"advanced"`
}

// supportedDBTypesForValidation is a test seam so unit tests can pin
// the list of drivers without rebuilding the binary. In production it
// always returns database.SupportedDBTypes().
var supportedDBTypesForValidation = database.SupportedDBTypes

func validateAdvancedConfig(cfg *AdvancedConfig) (string, bool) {
	if cfg == nil {
		return "", true
	}
	if cfg.DBType != "" {
		supported := false
		for _, t := range supportedDBTypesForValidation() {
			if t == cfg.DBType {
				supported = true
				break
			}
		}
		if !supported {
			return "advanced.dbType " + cfg.DBType + " is not supported by this build (supported: " + strings.Join(supportedDBTypesForValidation(), ", ") + ")", false
		}
	}
	if cfg.DBType == "mysql" {
		if strings.TrimSpace(cfg.DBHost) == "" {
			return "advanced.dbHost is required when dbType is mysql", false
		}
		if strings.TrimSpace(cfg.DBName) == "" {
			return "advanced.dbName is required when dbType is mysql", false
		}
		if strings.TrimSpace(cfg.DBUser) == "" {
			return "advanced.dbUser is required when dbType is mysql", false
		}
		if cfg.DBPort != "" {
			if port, err := strconv.Atoi(cfg.DBPort); err != nil || port < 1 || port > 65535 {
				return "advanced.dbPort must be a valid port number", false
			}
		}
	}
	if cfg.ServerPort != "" {
		if port, err := strconv.Atoi(cfg.ServerPort); err != nil || port < 1 || port > 65535 {
			return "advanced.serverPort must be a valid port number", false
		}
	}
	return "", true
}

// applyAdvancedToEnv mirrors renderAdvancedConfigEnv into the live process
// environment so the database package can read the freshly-supplied
// credentials when Init runs in first-run (db==nil) mode and bootstraps the
// connection itself. Only sets vars that are non-empty in cfg so it doesn't
// silently wipe pre-existing values.
func applyAdvancedToEnv(cfg *AdvancedConfig) {
	if cfg == nil {
		return
	}
	if v := strings.TrimSpace(cfg.DBType); v != "" {
		_ = os.Setenv("DB_TYPE", v)
	}
	if strings.EqualFold(strings.TrimSpace(cfg.DBType), "mysql") {
		if v := strings.TrimSpace(cfg.DBHost); v != "" {
			_ = os.Setenv("DB_HOST", v)
		}
		if v := strings.TrimSpace(cfg.DBPort); v != "" {
			_ = os.Setenv("DB_PORT", v)
		}
		if v := strings.TrimSpace(cfg.DBUser); v != "" {
			_ = os.Setenv("DB_USER", v)
		}
		_ = os.Setenv("DB_PASSWORD", cfg.DBPassword)
		if v := strings.TrimSpace(cfg.DBName); v != "" {
			_ = os.Setenv("DB_NAME", v)
		}
	} else if v := strings.TrimSpace(cfg.DBPath); v != "" {
		_ = os.Setenv("DATABASE_URL", v)
	}
	if v := strings.TrimSpace(cfg.ServerPort); v != "" {
		_ = os.Setenv("PORT", v)
	}
	if v := strings.TrimSpace(cfg.AllowedOrigins); v != "" {
		_ = os.Setenv("ALLOWED_ORIGINS", v)
	}
}

func renderAdvancedConfigEnv(cfg *AdvancedConfig) string {
	if cfg == nil {
		return ""
	}
	var b strings.Builder
	b.WriteString("# Generated by setup wizard\n")
	b.WriteString(fmt.Sprintf("DB_TYPE=%s\n", cfg.DBType))
	if cfg.DBType == "mysql" {
		b.WriteString(fmt.Sprintf("DB_HOST=%s\n", cfg.DBHost))
		if cfg.DBPort != "" {
			b.WriteString(fmt.Sprintf("DB_PORT=%s\n", cfg.DBPort))
		} else {
			b.WriteString("DB_PORT=3306\n")
		}
		b.WriteString(fmt.Sprintf("DB_USER=%s\n", cfg.DBUser))
		b.WriteString(fmt.Sprintf("DB_PASSWORD=%s\n", cfg.DBPassword))
		b.WriteString(fmt.Sprintf("DB_NAME=%s\n", cfg.DBName))
	} else if cfg.DBPath != "" {
		b.WriteString(fmt.Sprintf("DATABASE_URL=%s\n", cfg.DBPath))
	}
	// Always emit PORT and ALLOWED_ORIGINS, even when empty, so the
	// generated kanban.env is a complete reference of every knob the
	// setup wizard surfaced. Operators can edit the file later without
	// having to remember which fields exist.
	serverPort := cfg.ServerPort
	if serverPort == "" {
		serverPort = "8080"
	}
	b.WriteString(fmt.Sprintf("PORT=%s\n", serverPort))
	b.WriteString(fmt.Sprintf("ALLOWED_ORIGINS=%s\n", cfg.AllowedOrigins))
	return b.String()
}

// initConfigOutputPath returns the destination file path for the generated
// config. It honors the INIT_CONFIG_OUTPUT env var (for ops/testing) and
// defaults to ./kanban.env in the current working directory.
func initConfigOutputPath() (string, error) {
	if v := strings.TrimSpace(os.Getenv("INIT_CONFIG_OUTPUT")); v != "" {
		abs, err := filepath.Abs(v)
		if err != nil {
			return "", fmt.Errorf("invalid INIT_CONFIG_OUTPUT path: %v", err)
		}
		return abs, nil
	}
	wd, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("failed to get working directory: %v", err)
	}
	return filepath.Join(wd, "kanban.env"), nil
}

func writeAdvancedConfig(cfg *AdvancedConfig) (string, error) {
	if cfg == nil {
		return "", nil
	}
	path, err := initConfigOutputPath()
	if err != nil {
		return "", err
	}
	content := renderAdvancedConfigEnv(cfg)
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		return "", fmt.Errorf("failed to write config file: %v", err)
	}
	return path, nil
}

// defaultAdvancedForInit returns the AdvancedConfig the setup wizard
// would pre-fill if the operator had not touched the form. Used to
// make `init` always write a complete kanban.env — even when the
// caller omits the `advanced` field, the file ends up containing the
// same DB_TYPE / PORT / ALLOWED_ORIGINS the wizard would have
// produced.
func defaultAdvancedForInit() *AdvancedConfig {
	dbType := strings.ToLower(strings.TrimSpace(os.Getenv("DB_TYPE")))
	if dbType != "mysql" && dbType != "sqlite" {
		dbType = "sqlite"
	}
	return &AdvancedConfig{
		DBType:         dbType,
		DBPath:         getEnvDefault("DATABASE_URL", "kanban.db"),
		DBHost:         getEnvDefault("DB_HOST", "localhost"),
		DBPort:         getEnvDefault("DB_PORT", "3306"),
		DBUser:         getEnvDefault("DB_USER", "root"),
		DBPassword:     os.Getenv("DB_PASSWORD"),
		DBName:         getEnvDefault("DB_NAME", "kanban"),
		ServerPort:     getEnvDefault("PORT", "8080"),
		AllowedOrigins: os.Getenv("ALLOWED_ORIGINS"),
	}
}

// GetInitDefaults returns the server's currently-loaded config values so the
// setup wizard can pre-fill its advanced form. Values come from the process
// environment (which the kanban.env file has already populated at startup),
// so when the user runs with `-config kanban.env` the form starts with
// those values instead of generic defaults.
func GetInitDefaults() gin.HandlerFunc {
	return func(c *gin.Context) {
		dbType := strings.ToLower(os.Getenv("DB_TYPE"))
		if dbType != "mysql" {
			dbType = "sqlite"
		}
		port := os.Getenv("PORT")
		if port == "" {
			port = "8080"
		}
		dbPort := os.Getenv("DB_PORT")
		if dbPort == "" {
			dbPort = "3306"
		}
		c.JSON(http.StatusOK, gin.H{
			"dbType":           dbType,
			"dbPath":           getEnvDefault("DATABASE_URL", "kanban.db"),
			"dbHost":           getEnvDefault("DB_HOST", "localhost"),
			"dbPort":           dbPort,
			"dbUser":           getEnvDefault("DB_USER", "root"),
			"dbPassword":       os.Getenv("DB_PASSWORD"),
			"dbName":           getEnvDefault("DB_NAME", "kanban"),
			"serverPort":       port,
			"allowedOrigins":   os.Getenv("ALLOWED_ORIGINS"),
			"supportedDbTypes": database.SupportedDBTypes(),
		})
	}
}

func getEnvDefault(key, fallback string) string {
	if v := strings.TrimSpace(os.Getenv(key)); v != "" {
		return v
	}
	return fallback
}

func Init(db *sql.DB, onConfigPersisted func(path string)) gin.HandlerFunc {
	return func(c *gin.Context) {
		// Bind the request body ONCE. c.ShouldBindJSON consumes the
		// body stream, so a second call (as in earlier revisions that
		// peeked the body when db==nil) would fail with "Invalid
		// request format" and surface as a confusing 400 to the
		// setup wizard.
		var req InitRequest
		if err := c.ShouldBindJSON(&req); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid request format"})
			return
		}

		// First-run mode: the server couldn't connect to any database at
		// startup (no kanban.env / no DB env vars), so it skipped the
		// eager InitDB() call and registered only the setup routes.
		// Bootstrap a connection from the Advanced block in this request,
		// then proceed with the regular init flow on the now-connected db.
		if db == nil {
			if msg, ok := validateAdvancedConfig(req.Advanced); !ok {
				c.JSON(http.StatusBadRequest, gin.H{"error": msg})
				return
			}
			applyAdvancedToEnv(req.Advanced)
			// Re-read non-DB config so server-side knobs (rate limit,
			// websocket, etc.) match the values the user just chose.
			config.InitConfig()

			newDB, err := database.InitDB()
			if err != nil {
				log.Printf("[Init] failed to bootstrap database from advanced config: %v", err)
				c.JSON(http.StatusBadRequest, gin.H{
					"error": "Failed to connect to the database using the supplied Advanced settings. " +
						"Verify DB_HOST / DB_PORT / DB_USER / DB_PASSWORD / DB_NAME and that the server is reachable: " + err.Error(),
				})
				return
			}
			db = newDB
		}

		var userCount int
		err := db.QueryRow("SELECT COUNT(*) FROM users").Scan(&userCount)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to check user"})
			return
		}

		if userCount > 0 {
			c.JSON(http.StatusForbidden, gin.H{"error": "System already initialized, cannot set up again"})
			return
		}

		if req.Username == "" {
			c.JSON(http.StatusBadRequest, gin.H{"error": "Username is required"})
			return
		}

		var configPath string
		// Always persist kanban.env during init, even when the caller
		// omitted the `advanced` block, so the resulting config file is
		// a complete reference of every knob (DB_TYPE, PORT,
		// ALLOWED_ORIGINS, …) instead of a partial subset. Operators
		// can then edit the file later without wondering which fields
		// are missing.
		advancedToWrite := req.Advanced
		if advancedToWrite == nil {
			advancedToWrite = defaultAdvancedForInit()
		}
		if msg, ok := validateAdvancedConfig(advancedToWrite); !ok {
			c.JSON(http.StatusBadRequest, gin.H{"error": msg})
			return
		}
		path, err := writeAdvancedConfig(advancedToWrite)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to save advanced config: " + err.Error()})
			return
		}
		configPath = path

		nickname := req.Nickname
		if nickname == "" {
			nickname = req.Username
		}

		_, err = db.Exec(
			"REPLACE INTO app_config (`key`, value) VALUES ('allowRegistration', ?)",
			map[bool]string{true: "1", false: "0"}[req.AllowRegistration],
		)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to save configuration"})
			return
		}

		requirePassword := req.Password != ""
		_, err = db.Exec(
			"REPLACE INTO app_config (`key`, value) VALUES ('requirePassword', ?)",
			map[bool]string{true: "1", false: "0"}[requirePassword],
		)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to save configuration"})
			return
		}

		authEnabled := true
		if req.AuthEnabled != nil {
			authEnabled = *req.AuthEnabled
		}
		_, err = db.Exec(
			"REPLACE INTO app_config (`key`, value) VALUES ('authEnabled', ?)",
			map[bool]string{true: "1", false: "0"}[authEnabled],
		)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to save configuration"})
			return
		}

		avatar := req.Avatar

		var hashedPassword *string
		if req.Password != "" {
			hashed, err := hashWithSalt(req.Password)
			if err != nil {
				c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to encrypt password"})
				return
			}
			hashedPassword = &hashed
		}

		userID := generateID()
		_, err = db.Exec(
			"INSERT INTO users (id, username, nickname, password, avatar, type, role, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
			userID, req.Username, nickname, hashedPassword, avatar, "HUMAN", "ADMIN", time.Now(), time.Now(),
		)
		if err != nil {
			log.Printf("[Init] failed to insert admin user: %v", err)
			c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to create user: " + err.Error()})
			return
		}

		tokenKey := generateTokenKey()
		tokenID := generateID()
		_, err = db.Exec(
			"INSERT INTO tokens (id, name, `key`, user_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)",
			tokenID, "default", tokenKey, userID, time.Now(), time.Now(),
		)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to create session"})
			return
		}

		isSecure := c.Request.TLS != nil || c.GetHeader("X-Forwarded-Proto") == "https"
		c.SetCookie("kanban-token", tokenKey, 60*60*24*30, "/", "", isSecure, true)
		c.SetSameSite(http.SameSiteLaxMode)

		// If a config file was written, notify the caller so it can
		// restart the process with the new config. This happens after
		// the user/admin/token rows are persisted but before we write
		// the HTTP response, so the caller can shut down cleanly and
		// the response still flushes to the client first.
		if configPath != "" && onConfigPersisted != nil {
			onConfigPersisted(configPath)
		}

		c.JSON(http.StatusOK, gin.H{
			"user": gin.H{
				"id":       userID,
				"username": req.Username,
				"nickname": nickname,
				"avatar":   avatar,
				"type":     "HUMAN",
				"role":     "ADMIN",
			},
			"token":           tokenKey,
			"requirePassword": requirePassword,
			"configPath":      configPath,
			"restartRequired": false,
		})
	}
}

func Login(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		clientIP := c.ClientIP()
		if !checkRateLimit("login:" + clientIP) {
			c.JSON(http.StatusTooManyRequests, gin.H{"error": "Too many requests, please try again later"})
			return
		}

		var req LoginRequest
		if err := c.ShouldBindJSON(&req); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid request format"})
			return
		}

		username := req.Username
		if username == "" {
			c.JSON(http.StatusBadRequest, gin.H{"error": "Username is required"})
			return
		}

		if !checkRateLimit("login:" + username) {
			c.JSON(http.StatusTooManyRequests, gin.H{"error": "Too many requests, please try again later"})
			return
		}

		var existingUser struct {
			ID       string
			Password string
			Username string
			Nickname string
			Avatar   string
			UserType string
			Role     string
		}

		err := db.QueryRow(
			"SELECT id, password, username, nickname, avatar, type, role FROM users WHERE username = ?",
			username,
		).Scan(&existingUser.ID, &existingUser.Password, &existingUser.Username, &existingUser.Nickname, &existingUser.Avatar, &existingUser.UserType, &existingUser.Role)

		if err == sql.ErrNoRows {
			var userCount int
			err := db.QueryRow("SELECT COUNT(*) FROM users").Scan(&userCount)
			if err != nil {
				c.JSON(http.StatusInternalServerError, gin.H{"error": "Login failed"})
				return
			}

			if userCount > 0 {
				var allowRegistration string
				err := db.QueryRow("SELECT value FROM app_config WHERE `key` = 'allowRegistration'").Scan(&allowRegistration)
				if err == nil && allowRegistration == "0" {
					c.JSON(http.StatusForbidden, gin.H{"error": "Registration is closed, please contact admin to add user"})
					return
				}
			}

			isFirstUser := userCount == 0

			avatar := req.Avatar

			userType := req.Type
			if userType == "" {
				userType = "HUMAN"
			}
			role := "MEMBER"
			if isFirstUser {
				role = "ADMIN"
			}

			var hashedPassword *string
			if req.Password != "" {
				hashed, err := hashWithSalt(req.Password)
				if err != nil {
					c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to encrypt password"})
					return
				}
				hashedPassword = &hashed
			}

			userID := generateID()
			_, err = db.Exec(
				"INSERT INTO users (id, username, nickname, password, avatar, type, role, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
				userID, username, username, hashedPassword, avatar, userType, role, time.Now(), time.Now(),
			)
			if err != nil {
				log.Printf("[Login] failed to auto-create user: %v", err)
				c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to create user: " + err.Error()})
				return
			}

			LogActivity(db, userID, "USER_CREATE", "USER", userID, username, "", c.ClientIP(), getRequestSource(c))

			tokenKey := generateTokenKey()
			tokenID := generateID()
			_, err = db.Exec(
				"INSERT INTO tokens (id, name, `key`, user_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)",
				tokenID, "default", tokenKey, userID, time.Now(), time.Now(),
			)
			if err != nil {
				c.JSON(http.StatusInternalServerError, gin.H{"error": "Login failed"})
				return
			}

			if isFirstUser {
				rows, err := db.Query("SELECT id FROM boards WHERE deleted = false")
				if err == nil {
					defer rows.Close()
					for rows.Next() {
						var boardID string
						if err := rows.Scan(&boardID); err == nil {
							permID := generateID()
							db.Exec(
								"INSERT INTO board_permissions (id, user_id, board_id, access) VALUES (?, ?, ?, ?)",
								permID, userID, boardID, "ADMIN",
							)
						}
					}
				}
			}

			isSecure := c.Request.TLS != nil || c.GetHeader("X-Forwarded-Proto") == "https"
			c.SetCookie("kanban-token", tokenKey, 60*60*24*30, "/", "", isSecure, true)
			c.SetSameSite(http.SameSiteLaxMode)

			c.JSON(http.StatusOK, gin.H{
				"user": gin.H{
					"id":       userID,
					"username": username,
					"nickname": username,
					"avatar":   avatar,
					"type":     userType,
					"role":     role,
				},
				"token": tokenKey,
			})
			return
		} else if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "Login failed"})
			return
		}

		if existingUser.Password != "" && req.Password == "" {
			c.JSON(http.StatusUnauthorized, gin.H{
				"error":           "Password is required",
				"requirePassword": true,
			})
			return
		}

		if existingUser.Password != "" {
			if !verifyWithSalt(req.Password, existingUser.Password) {
				c.JSON(http.StatusUnauthorized, gin.H{"error": "Incorrect password"})
				return
			}
		}

		tokenKey := generateTokenKey()
		tokenID := generateID()
		_, err = db.Exec(
			"INSERT INTO tokens (id, name, `key`, user_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)",
			tokenID, "default", tokenKey, existingUser.ID, time.Now(), time.Now(),
		)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "Login failed"})
			return
		}

		isSecure := c.Request.TLS != nil || c.GetHeader("X-Forwarded-Proto") == "https"
		c.SetCookie("kanban-token", tokenKey, 60*60*24*30, "/", "", isSecure, true)
		c.SetSameSite(http.SameSiteLaxMode)

		LogActivity(db, existingUser.ID, "LOGIN", "USER", existingUser.ID, existingUser.Nickname, "", c.ClientIP(), getRequestSource(c))

		var requirePassword bool = false
		var requirePasswordVal string
		if err := db.QueryRow("SELECT value FROM app_config WHERE `key` = 'requirePassword'").Scan(&requirePasswordVal); err == nil {
			requirePassword = requirePasswordVal == "1"
		}

		c.JSON(http.StatusOK, gin.H{
			"user": gin.H{
				"id":       existingUser.ID,
				"username": existingUser.Username,
				"nickname": existingUser.Nickname,
				"avatar":   existingUser.Avatar,
				"type":     existingUser.UserType,
				"role":     existingUser.Role,
			},
			"token":           tokenKey,
			"requirePassword": requirePassword,
		})
	}
}

func GetAvatars() gin.HandlerFunc {
	return func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"avatars": avatarOptions})
	}
}

func GetMe(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		// Lazy-setup mode: the server skipped InitDB() at startup because no
		// MySQL credentials were configured. We have no DB to query, so
		// signal the SPA that the wizard must run. The frontend's
		// HomeRedirect relies on needsSetup=true to forward to /setup.
		if db == nil {
			c.JSON(http.StatusOK, gin.H{
				"user":              nil,
				"needsSetup":        true,
				"allowRegistration": true,
			})
			return
		}

		var requirePasswordVal string
		var isRequirePassword bool = false
		if err := db.QueryRow("SELECT value FROM app_config WHERE `key` = 'requirePassword'").Scan(&requirePasswordVal); err == nil {
			isRequirePassword = requirePasswordVal == "1"
		}

		var userCount int
		err := db.QueryRow("SELECT COUNT(*) FROM users").Scan(&userCount)
		if err != nil || userCount == 0 {
			c.JSON(http.StatusOK, gin.H{
				"user":              nil,
				"needsSetup":        true,
				"allowRegistration": true,
				"requirePassword":   isRequirePassword,
			})
			return
		}

		tokenKey, err := c.Cookie("kanban-token")
		if err != nil {
			c.JSON(http.StatusUnauthorized, gin.H{
				"user":            nil,
				"needsSetup":      false,
				"requirePassword": isRequirePassword,
			})
			return
		}

		user := getCurrentUserFromToken(db, tokenKey)
		if user == nil {
			c.JSON(http.StatusUnauthorized, gin.H{
				"user":            nil,
				"needsSetup":      false,
				"requirePassword": isRequirePassword,
			})
			return
		}

		rows, err := db.Query(
			"SELECT bp.board_id, b.name, bp.access FROM board_permissions bp JOIN boards b ON bp.board_id = b.id WHERE bp.user_id = ?",
			user.ID,
		)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to get user info"})
			return
		}
		defer rows.Close()

		var permissions []gin.H
		for rows.Next() {
			var boardID, boardName, access string
			if err := rows.Scan(&boardID, &boardName, &access); err == nil {
				permissions = append(permissions, gin.H{
					"boardId":   boardID,
					"boardName": boardName,
					"access":    access,
				})
			}
		}

		var allowRegistration bool = true
		var requirePassword bool = false
		var authEnabled bool = true
		db.QueryRow("SELECT value FROM app_config WHERE `key` = 'allowRegistration'").Scan(&allowRegistration)
		db.QueryRow("SELECT value FROM app_config WHERE `key` = 'requirePassword'").Scan(&requirePassword)
		db.QueryRow("SELECT value FROM app_config WHERE `key` = 'authEnabled'").Scan(&authEnabled)

		c.JSON(http.StatusOK, gin.H{
			"user": gin.H{
				"id":       user.ID,
				"username": user.Username,
				"nickname": user.Nickname,
				"avatar":   user.Avatar,
				"type":     user.Type,
				"role":     user.Role,
			},
			"permissions":       permissions,
			"needsSetup":        false,
			"allowRegistration": allowRegistration,
			"requirePassword":   requirePassword,
			"authEnabled":       authEnabled,
		})
	}
}

func getCurrentUserFromToken(db *sql.DB, tokenKey string) *models.User {
	if cached, ok := tokenCache.Load(tokenKey); ok {
		if time.Now().Before(cached.expiresAt) && cached.user.Enabled {
			return cached.user
		}
	}

	var user models.User
	var token models.Token
	err := db.QueryRow(
		"SELECT t.id, t.expires_at, u.id, u.username, u.nickname, u.avatar, u.type, u.role, u.enabled FROM tokens t JOIN users u ON t.user_id = u.id WHERE t.`key` = ?",
		tokenKey,
	).Scan(&token.ID, &token.ExpiresAt, &user.ID, &user.Username, &user.Nickname, &user.Avatar, &user.Type, &user.Role, &user.Enabled)
	if err != nil {
		return nil
	}

	if token.ExpiresAt != nil && token.ExpiresAt.Before(time.Now()) {
		return nil
	}

	if !user.Enabled {
		return nil
	}

	db.Exec("UPDATE users SET last_active_at = datetime('now') WHERE id = ?", user.ID)

	tokenCache.Store(tokenKey, &cachedUser{
		user:      &user,
		expiresAt: time.Now().Add(tokenCacheDuration),
	})

	return &user
}
