package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

func main() {
	if len(os.Args) < 2 {
		printUsage()
		os.Exit(1)
	}

	switch os.Args[1] {
	case "create-config":
		createConfigCmd := flag.NewFlagSet("create-config", flag.ExitOnError)
		outputPath := createConfigCmd.String("o", "", "Output path (default: /tmp/kanban.env)")
		dbType := createConfigCmd.String("db", "sqlite", "Database type: sqlite or mysql")
		_ = createConfigCmd.Parse(os.Args[2:])
		createConfig(*outputPath, *dbType)

	case "verify-config":
		verifyConfigCmd := flag.NewFlagSet("verify-config", flag.ExitOnError)
		configPath := verifyConfigCmd.String("f", "", "Path to config file to verify")
		_ = verifyConfigCmd.Parse(os.Args[2:])
		if *configPath == "" {
			fmt.Println("Error: -f flag is required")
			printUsage()
			os.Exit(1)
		}
		verifyConfig(*configPath)

	case "test-startup":
		testStartupCmd := flag.NewFlagSet("test-startup", flag.ExitOnError)
		configPath := testStartupCmd.String("f", "", "Path to config file to test")
		_ = testStartupCmd.Parse(os.Args[2:])
		if *configPath == "" {
			fmt.Println("Error: -f flag is required")
			printUsage()
			os.Exit(1)
		}
		testStartup(*configPath)

	case "help", "--help":
		printUsage()

	default:
		fmt.Printf("Unknown command: %s\n", os.Args[1])
		printUsage()
		os.Exit(1)
	}
}

func printUsage() {
	fmt.Println("kanban-config - Configuration tool for kanban server")
	fmt.Println("")
	fmt.Println("Usage:")
	fmt.Println("  kanban-config <command> [options]")
	fmt.Println("")
	fmt.Println("Commands:")
	fmt.Println("  create-config     Create a new configuration file")
	fmt.Println("  verify-config     Verify a configuration file is valid")
	fmt.Println("  test-startup      Test that server startup reads config correctly")
	fmt.Println("  help              Show this help message")
	fmt.Println("")
	fmt.Println("create-config options:")
	fmt.Println("  -o <path>   Output path (default: /tmp/kanban.env)")
	fmt.Println("  -db <type>  Database type: sqlite or mysql (default: sqlite)")
	fmt.Println("")
	fmt.Println("verify-config options:")
	fmt.Println("  -f <path>   Path to config file to verify (required)")
	fmt.Println("")
	fmt.Println("test-startup options:")
	fmt.Println("  -f <path>   Path to config file to test (required)")
}

func createConfig(outputPath string, dbType string) {
	if outputPath == "" {
		outputPath = "/tmp/kanban.env"
	}

	if dbType != "sqlite" && dbType != "mysql" {
		fmt.Printf("Error: invalid database type %s (must be 'sqlite' or 'mysql')\n", dbType)
		os.Exit(1)
	}

	var configContent string
	if dbType == "sqlite" {
		configContent = `# Kanban Server Configuration
# Generated by kanban-config tool

# Server port (default: 8080)
PORT=8080

# Database type: sqlite or mysql
DB_TYPE=sqlite

# SQLite database file path
DATABASE_URL=kanban.db

# WebSocket configuration
WS_PING_INTERVAL=30
WS_PING_WRITE_DEADLINE=10
WS_READ_DEADLINE=40
WS_MAX_CONNECTIONS=0
WS_MAX_CONNECTIONS_PER_USER=0

# Rate limiting (0 = disabled)
RATE_LIMIT_MAX_ENTRIES=0
GLOBAL_RATE_LIMIT_MAX_ENTRIES=0

# Broadcast configuration
BROADCAST_WRITE_DEADLINE=2

# Webhook configuration
WEBHOOK_TIMEOUT=10

# CORS configuration
ALLOWED_ORIGINS=

# Static web directory (leave empty for embedded)
WEB_DIR=
`
	} else {
		configContent = `# Kanban Server Configuration
# Generated by kanban-config tool

# Server port (default: 8080)
PORT=8080

# Database type: sqlite or mysql
DB_TYPE=mysql

# MySQL database configuration
DB_HOST=localhost
DB_PORT=3306
DB_USER=root
DB_PASSWORD=
DB_NAME=kanban
DB_MAX_OPEN_CONNS=25
DB_MAX_IDLE_CONNS=5
DB_CONN_MAX_LIFETIME=300

# WebSocket configuration
WS_PING_INTERVAL=30
WS_PING_WRITE_DEADLINE=10
WS_READ_DEADLINE=40
WS_MAX_CONNECTIONS=0
WS_MAX_CONNECTIONS_PER_USER=0

# Rate limiting (0 = disabled)
RATE_LIMIT_MAX_ENTRIES=0
GLOBAL_RATE_LIMIT_MAX_ENTRIES=0

# Broadcast configuration
BROADCAST_WRITE_DEADLINE=2

# Webhook configuration
WEBHOOK_TIMEOUT=10

# CORS configuration
ALLOWED_ORIGINS=

# Static web directory (leave empty for embedded)
WEB_DIR=
`
	}

	dir := filepath.Dir(outputPath)
	if err := os.MkdirAll(dir, 0750); err != nil {
		fmt.Printf("Error: failed to create directory %s: %v\n", dir, err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputPath, []byte(configContent), 0600); err != nil {
		fmt.Printf("Error: failed to write config file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Configuration file created successfully at: %s\n", outputPath)
}

func verifyConfig(configPath string) {
	if _, err := os.Stat(configPath); err != nil {
		fmt.Printf("Error: config file not found: %v\n", err)
		os.Exit(1)
	}
	data, err := os.ReadFile(configPath)
	if err != nil {
		fmt.Printf("Error: failed to read config file: %v\n", err)
		os.Exit(1)
	}

	lines := strings.Split(string(data), "\n")
	errors := []string{}
	warnings := []string{}
	validDBTypes := map[string]bool{"sqlite": true, "mysql": true}

	for lineNum, line := range lines {
		lineNum++
		line = strings.TrimSpace(line)

		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			errors = append(errors, fmt.Sprintf("Line %d: invalid format (missing '=')", lineNum))
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])

		if key == "" {
			errors = append(errors, fmt.Sprintf("Line %d: empty key", lineNum))
			continue
		}

		switch key {
		case "PORT":
			if _, err := strconv.Atoi(value); err != nil {
				errors = append(errors, fmt.Sprintf("Line %d: PORT must be a valid number", lineNum))
			} else if port, _ := strconv.Atoi(value); port < 1 || port > 65535 {
				errors = append(errors, fmt.Sprintf("Line %d: PORT must be between 1 and 65535", lineNum))
			}

		case "DB_TYPE":
			if !validDBTypes[value] {
				errors = append(errors, fmt.Sprintf("Line %d: DB_TYPE must be 'sqlite' or 'mysql'", lineNum))
			}

		case "DB_PORT":
			if _, err := strconv.Atoi(value); err != nil {
				errors = append(errors, fmt.Sprintf("Line %d: DB_PORT must be a valid number", lineNum))
			}

		case "DB_MAX_OPEN_CONNS", "DB_MAX_IDLE_CONNS", "DB_CONN_MAX_LIFETIME":
			if _, err := strconv.Atoi(value); err != nil {
				errors = append(errors, fmt.Sprintf("Line %d: %s must be a valid number", lineNum, key))
			}

		case "WS_PING_INTERVAL", "WS_PING_WRITE_DEADLINE", "WS_READ_DEADLINE":
			if _, err := strconv.Atoi(value); err != nil {
				warnings = append(warnings, fmt.Sprintf("Line %d: %s should be a number (seconds)", lineNum, key))
			}

		case "RATE_LIMIT_MAX_ENTRIES", "GLOBAL_RATE_LIMIT_MAX_ENTRIES":
			if _, err := strconv.Atoi(value); err != nil {
				errors = append(errors, fmt.Sprintf("Line %d: %s must be a valid number", lineNum, key))
			}

		case "WEBHOOK_TIMEOUT":
			if _, err := strconv.Atoi(value); err != nil {
				warnings = append(warnings, fmt.Sprintf("Line %d: WEBHOOK_TIMEOUT should be a number (seconds)", lineNum))
			}

		case "BROADCAST_WRITE_DEADLINE":
			if _, err := strconv.Atoi(value); err != nil {
				warnings = append(warnings, fmt.Sprintf("Line %d: BROADCAST_WRITE_DEADLINE should be a number (seconds)", lineNum))
			}
		}
	}

	if len(warnings) > 0 {
		fmt.Println("Warnings:")
		for _, w := range warnings {
			fmt.Printf("  - %s\n", w)
		}
		fmt.Println("")
	}

	if len(errors) > 0 {
		fmt.Println("Errors found:")
		for _, e := range errors {
			fmt.Printf("  - %s\n", e)
		}
		os.Exit(1)
	}

	fmt.Println("Configuration file is valid!")
	fmt.Printf("Verified: %s\n", configPath)
}

func testStartup(configPath string) {
	if _, err := os.Stat(configPath); err != nil {
		fmt.Printf("Error: config file not found: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Testing server startup with config file...")
	fmt.Printf("Config file: %s\n\n", configPath)

	data, err := os.ReadFile(configPath)
	if err != nil {
		fmt.Printf("Error: failed to read config file: %v\n", err)
		os.Exit(1)
	}

	envVars := make(map[string]string)
	lines := strings.Split(string(data), "\n")
	for lineNum, line := range lines {
		lineNum++
		line = strings.TrimSpace(line)

		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			fmt.Printf("Warning: Line %d: invalid format\n", lineNum)
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])
		envVars[key] = value
	}

	fmt.Println("Environment variables that would be set:")
	fmt.Println("  Database type:", envVars["DB_TYPE"])
	fmt.Println("  Database URL/Path:", envVars["DATABASE_URL"])
	fmt.Println("  Port:", envVars["PORT"])

	if envVars["DB_TYPE"] == "mysql" {
		fmt.Println("  MySQL Host:", envVars["DB_HOST"])
		fmt.Println("  MySQL Port:", envVars["DB_PORT"])
		fmt.Println("  MySQL User:", envVars["DB_USER"])
		fmt.Println("  MySQL Database:", envVars["DB_NAME"])
	}

	fmt.Println("")
	fmt.Println("Note: To actually test startup, the server would need to be run with these env vars.")
	fmt.Println("This tool only verifies the config file format is correct for startup.")
}
