package main

import (
	"context"
	"database/sql"
	"embed"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"log"
	"net/http"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"open-kanban/internal/config"
	"open-kanban/internal/database"
	"open-kanban/internal/handlers"
	"open-kanban/internal/oauth"
	"open-kanban/internal/services"

	"github.com/gin-gonic/gin"
)

func loadEnvFromFile(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("failed to read config file: %w", err)
	}

	lines := strings.Split(string(data), "\n")
	for lineNum, line := range lines {
		lineNum++
		line = strings.TrimSpace(line)

		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			log.Printf("Warning: Line %d: invalid format in config file\n", lineNum)
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])

		if key == "" {
			log.Printf("Warning: Line %d: empty key in config file\n", lineNum)
			continue
		}

		if _, exists := os.LookupEnv(key); !exists {
			if err := os.Setenv(key, value); err != nil {
				log.Printf("Warning: Failed to set environment variable %s: %v\n", key, err)
			}
		}
	}

	return nil
}

//go:embed web
var embeddedWeb embed.FS

// mysqlNeedsLazySetup reports whether the server is starting on a MySQL
// database with no connection details available, in which case we should
// skip the eager InitDB() call at startup and let the setup wizard supply
// the credentials. SQLite is never "needing lazy setup" because it just
// creates an empty file on disk if one doesn't exist.
//
// Returns false unless DB_TYPE resolves to "mysql" AND neither DB_HOST nor
// DB_USER is set in the environment. If the user explicitly configured
// MySQL with partial env vars, we still attempt to connect and let it
// fail with a clear error rather than silently entering setup mode.
func mysqlNeedsLazySetup() bool {
	dbType := strings.ToLower(strings.TrimSpace(os.Getenv("DB_TYPE")))
	if dbType == "" {
		// Defaults differ between builds: db_mysql.go defaults to
		// "mysql" and db.go defaults to "sqlite". We can't tell which
		// build we're in at runtime, so probe the binary's behavior by
		// asking: would InitDB fail without any env vars?
		// Practically the only build that fails without env vars is the
		// MySQL-only one, so the safe heuristic is "treat unset DB_TYPE
		// as a normal SQLite-style startup".
		return false
	}
	if dbType != "mysql" {
		return false
	}
	return os.Getenv("DB_HOST") == "" && os.Getenv("DB_USER") == ""
}
// args and returns it together with the args surrounding it (before AND
// after, so flags like -yes that come after the subcommand still reach
// the subcommand's FlagSet). If none is found the empty string is
// returned, signalling that the caller should fall through to the
// long-running server path.
func detectSubcommand(args []string) (string, []string) {
	known := map[string]bool{
		"reset-password": true,
		"reset-system":   true,
		"help":           true,
		"--help":         true,
	}
	for i, a := range args {
		if known[a] {
			return a, append([]string{}, args[:i]...)
		}
	}
	return "", nil
}

// indexOf returns the position of needle in haystack, or -1 if missing.
func indexOf(haystack []string, needle string) int {
	for i, s := range haystack {
		if s == needle {
			return i
		}
	}
	return -1
}

// extractFlag returns the value associated with `-name <value>` or
// `-name=<value>` from args. The boolean indicates whether the flag was
// present at all.
func extractFlag(args []string, name string) (string, bool) {
	prefix := "-" + name + "="
	for _, a := range args {
		if strings.HasPrefix(a, prefix) {
			return strings.TrimPrefix(a, prefix), true
		}
	}
	for i, a := range args {
		if a == "-"+name && i+1 < len(args) {
			return args[i+1], true
		}
	}
	return "", false
}

// removeFlag strips `-name <value>` or `-name=<value>` occurrences from
// args so the resulting slice is safe to hand to a FlagSet that doesn't
// know about the global `-config` flag.
func removeFlag(args []string, name string) []string {
	out := make([]string, 0, len(args))
	skipNext := false
	prefix := "-" + name + "="
	for _, a := range args {
		if skipNext {
			skipNext = false
			continue
		}
		if strings.HasPrefix(a, prefix) {
			continue
		}
		if a == "-"+name {
			skipNext = true
			continue
		}
		out = append(out, a)
	}
	return out
}

// autoDetectConfig looks for a config file generated by the setup wizard in
// the current working directory. It returns the absolute path to the file if
// found, or an empty string otherwise. Used as a convenience so users that
// completed setup don't need to remember to pass -config on every restart.
func autoDetectConfig() string {
	candidates := []string{"kanban.env", ".env"}
	for _, name := range candidates {
		wd, err := os.Getwd()
		if err != nil {
			continue
		}
		path := filepath.Join(wd, name)
		if info, err := os.Stat(path); err == nil && !info.IsDir() {
			abs, err := filepath.Abs(path)
			if err != nil {
				return path
			}
			return abs
		}
	}
	return ""
}

// TriggerSelfRestart signals the running server to shut down gracefully and
// spawns a replacement process using the same executable and CLI args. The
// new process inherits the environment, so it picks up the freshly-written
// kanban.env automatically. The replacement process becomes a detached
// process group so it survives the parent's exit.
func TriggerSelfRestart(reason string) {
	exe, err := os.Executable()
	if err != nil {
		log.Printf("self-restart: failed to resolve executable: %v", err)
		return
	}
	args := os.Args[1:]
	cmd := exec.Command(exe, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = nil
	cmd.Env = os.Environ()
	if reason != "" {
		log.Printf("self-restart: %s", reason)
	}
	if err := cmd.Start(); err != nil {
		log.Printf("self-restart: failed to spawn replacement process: %v", err)
		return
	}
	log.Printf("self-restart: replacement process started with PID %d", cmd.Process.Pid)
	// Detach so the replacement process doesn't wait on us exiting.
	_ = cmd.Process.Release()
}

func corsMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		origin := c.Request.Header.Get("Origin")

		c.Writer.Header().Set("Vary", "Origin")

		allowedOrigins := handlers.GetAllowedOrigins()

		isAllowed := false
		allowedOrigin := ""
		for _, allowed := range allowedOrigins {
			if origin == allowed {
				isAllowed = true
				allowedOrigin = allowed
				break
			}
		}

		if isAllowed {
			c.Writer.Header().Set("Access-Control-Allow-Origin", allowedOrigin)
			c.Writer.Header().Set("Access-Control-Allow-Credentials", "true")
		}

		c.Writer.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		c.Writer.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization")

		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(204)
			return
		}
		c.Next()
	}
}

// setupOnlyRoutes registers the minimal endpoint set needed by the setup
// wizard. None of these handlers require a connected database; the Init
// handler itself bootstraps the connection from the Advanced block in the
// request body the first time it's called. Everything else (login, boards,
// tasks, OAuth, …) is intentionally left unregistered so unauthenticated
// callers can't probe it before setup completes.
func setupOnlyRoutes(r *gin.Engine, onConfigPersisted func(path string)) {
	auth := r.Group("/api/v1/auth")
	{
		auth.POST("/init", handlers.Init(nil, onConfigPersisted))
		auth.GET("/init-defaults", handlers.GetInitDefaults())
		auth.GET("/login", handlers.GetAvatars())
		auth.GET("/avatars", handlers.GetAvatars())
		// /me is intentionally registered here so the frontend's HomeRedirect
		// can detect needsSetup=true and auto-route to /setup. GetMe handles
		// a nil DB by returning the "setup needed" payload without touching
		// the database, so it is safe to call before the wizard runs.
		auth.GET("/me", handlers.GetMe(nil))
	}
}

func setupAPIRoutes(r *gin.Engine, db *sql.DB, onConfigPersisted func(path string)) {
	signer := oauth.NewSigner(db)
	if err := signer.LoadOrGenerate(); err != nil {
		log.Fatalf("failed to load OAuth signing key: %v", err)
	}
	if err := oauth.EnsureDefaults(db); err != nil {
		log.Fatalf("failed to seed OAuth defaults: %v", err)
	}

	// OAuth 2.1 discovery + JWKS
	r.GET("/.well-known/oauth-authorization-server", oauth.DiscoveryHandler("/oauth/device/code"))
	r.GET("/.well-known/oauth-protected-resource/mcp", oauth.ProtectedResourceHandler())
	r.GET("/.well-known/jwks.json", oauth.JWKSHandler(signer))

	// OAuth 2.1 endpoints (gated by oauth_enabled app_config)
	oauthGate := gin.HandlerFunc(func(c *gin.Context) {
		if !oauth.IsOAuthEnabled(db) {
			c.AbortWithStatusJSON(http.StatusServiceUnavailable, gin.H{
				"error":             "oauth_disabled",
				"error_description": "OAuth 2.1 is disabled by administrator.",
			})
			return
		}
		c.Next()
	})
	oauthGroup := r.Group("/oauth", oauthGate)
	oauthGroup.POST("/register", oauth.RegisterClient(db))
	oauthGroup.POST("/device/code", oauth.RequestDeviceCode(db))
	oauthGroup.POST("/token", oauth.TokenEndpoint(db, signer))
	oauthGroup.GET("/device/lookup", oauth.DeviceLookupHandler(db))
	oauthGroup.POST("/device/approve", handlers.RequireAuth(db), oauth.DeviceApproveHandler(db))

	auth := r.Group("/api/v1/auth")
	{
		auth.POST("/login", handlers.Login(db))
		auth.POST("/init", handlers.Init(db, onConfigPersisted))
		auth.GET("/init-defaults", handlers.GetInitDefaults())
		auth.GET("/login", handlers.GetAvatars())
		auth.GET("/avatars", handlers.GetAvatars())
		auth.GET("/me", handlers.GetMe(db))
		auth.GET("/config", handlers.GetAppConfig(db))
	}

	authProtected := r.Group("/api/v1/auth")
	authProtected.Use(handlers.RequireSignatureVerification(), handlers.RequireAuth(db))
	{
		authProtected.GET("/token", handlers.GetTokens(db))
		authProtected.POST("/token", handlers.CreateToken(db))
		authProtected.PUT("/token", handlers.UpdateToken(db))
		authProtected.DELETE("/token", handlers.DeleteToken(db))
		authProtected.GET("/activities", handlers.GetActivities(db))
		authProtected.GET("/agents", handlers.GetAgents(db))
		authProtected.POST("/agents", handlers.CreateAgent(db))
		authProtected.POST("/agents/reset-token", handlers.ResetAgentToken(db))
		authProtected.DELETE("/agents", handlers.DeleteAgent(db))
		authProtected.GET("/users", handlers.GetUsers(db))
		authProtected.PUT("/users", handlers.UpdateUser(db))
		authProtected.POST("/users", handlers.CreateUser(db))
		authProtected.POST("/users/enabled", handlers.SetUserEnabled(db))
		authProtected.GET("/permissions", handlers.GetPermissions(db))
		authProtected.POST("/permissions", handlers.SetPermission(db))
		authProtected.DELETE("/permissions", handlers.DeletePermission(db))
		authProtected.GET("/permissions/columns", handlers.GetColumnPermissions(db))
		authProtected.POST("/permissions/columns", handlers.SetColumnPermission(db))
		authProtected.DELETE("/permissions/columns", handlers.DeleteColumnPermission(db))
		authProtected.PUT("/config", handlers.UpdateAppConfig(db))
		// OAuth 2.1 admin endpoints
		authProtected.GET("/oauth/clients", oauth.ListAdminClientsHandler(db))
		authProtected.DELETE("/oauth/clients", oauth.DeleteAdminClientHandler(db))
		authProtected.GET("/oauth/consents", oauth.ListConsentsHandler(db))
		authProtected.DELETE("/oauth/consents", oauth.RevokeConsentHandler(db))
		authProtected.GET("/oauth/config", oauth.GetOAuthConfigHandler(db))
		authProtected.PUT("/oauth/config", oauth.UpdateOAuthConfigHandler(db))
	}

	boards := r.Group("/api/v1/boards")
	{
		boards.GET("", handlers.GetBoards(db))
		boards.GET("/:id", handlers.GetBoard(db))
		boards.Use(handlers.RequireSignatureVerification(), handlers.RequireAuth(db))
		boards.POST("", handlers.CreateBoard(db))
		boards.POST("/from-template", handlers.CreateBoardFromTemplate(db))
		boards.PUT("/:id", handlers.UpdateBoard(db))
		boards.DELETE("/:id", handlers.DeleteBoard(db))
		boards.GET("/:id/export", handlers.ExportBoard(db))
		boards.POST("/:id/copy", handlers.CopyBoard(db))
		boards.POST("/:id/reset", handlers.ResetBoard(db))
		boards.POST("/import", handlers.ImportBoard(db))
	}

	templates := r.Group("/api/v1/templates")
	templates.Use(handlers.RequireSignatureVerification(), handlers.RequireAuth(db))
	{
		templates.GET("", handlers.GetTemplates(db))
		templates.POST("", handlers.SaveTemplate(db))
		templates.DELETE("/:id", handlers.DeleteTemplate(db))
	}

	columns := r.Group("/api/v1/columns")
	{
		columns.GET("", handlers.GetColumns(db))
		columns.GET("/slug", handlers.GetColumnSlug(db))
		columns.Use(handlers.RequireSignatureVerification(), handlers.RequireAuth(db))
		columns.POST("", handlers.CreateColumn(db))
		columns.PUT("", handlers.UpdateColumn(db))
		columns.PUT("/reorder", handlers.ReorderColumns(db))
		columns.DELETE("", handlers.DeleteColumn(db))
		columns.GET("/:columnId/agent", handlers.GetColumnAgent(db))
		columns.POST("/:columnId/agent", handlers.SetColumnAgent(db))
		columns.DELETE("/:columnId/agent", handlers.DeleteColumnAgent(db))
	}

	tasks := r.Group("/api/v1/tasks")
	{
		tasks.GET("", handlers.GetTasks(db))
		tasks.GET("/search", handlers.SearchTasks(db))
		tasks.GET("/:id", handlers.GetTask(db))
		tasks.Use(handlers.RequireSignatureVerification(), handlers.RequireAuth(db))
		tasks.POST("", handlers.CreateTask(db))
		tasks.POST("/batch", handlers.BatchCreateTasks(db))
		tasks.PUT("/batch", handlers.BatchUpdateTasks(db))
		tasks.DELETE("/batch", handlers.BatchDeleteTasks(db))
		tasks.PUT("/:id", handlers.UpdateTask(db))
		tasks.DELETE("/:id", handlers.DeleteTask(db))
		tasks.POST("/:id/archive", handlers.ArchiveTask(db))
		tasks.POST("/:id/complete", handlers.CompleteTask(db))
		tasks.GET("/:id/attachments", handlers.RequireAuth(db), handlers.GetTaskAttachments(db))
	}

	r.GET("/api/v1/mcp/my-tasks", handlers.RequireSignatureVerification(), handlers.RequireAuth(db), handlers.GetMyTasks(db))

	comments := r.Group("/api/v1/comments")
	{
		comments.GET("", handlers.GetComments(db))
		comments.GET("/:id", handlers.GetComment(db))
		comments.Use(handlers.RequireSignatureVerification(), handlers.RequireAuth(db))
		comments.POST("", handlers.CreateComment(db))
	}

	subtasks := r.Group("/api/v1/subtasks")
	subtasks.Use(handlers.RequireSignatureVerification(), handlers.RequireAuth(db))
	{
		subtasks.GET("", handlers.GetSubtasks(db))
		subtasks.POST("", handlers.CreateSubtask(db))
		subtasks.PUT("/:id", handlers.UpdateSubtask(db))
		subtasks.DELETE("/:id", handlers.DeleteSubtask(db))
	}

	r.GET("/api/v1/archived", handlers.RequireSignatureVerification(), handlers.RequireAuth(db), handlers.GetArchivedTasks(db))
	r.GET("/api/v1/drafts", handlers.RequireSignatureVerification(), handlers.RequireAuth(db), handlers.GetDrafts(db))

	dashboard := r.Group("/api/v1/dashboard")
	dashboard.Use(handlers.RequireSignatureVerification(), handlers.RequireAuth(db))
	{
		dashboard.GET("/stats", handlers.GetDashboardStats(db))
	}

	webhook := r.Group("/api/v1/webhook")
	webhook.Use(handlers.RequireSignatureVerification(), handlers.RequireAuth(db))
	{
		webhook.POST("/notify", handlers.WebhookNotify(db))
	}

	r.POST("/api/v1/upload", handlers.RequireSignatureVerification(), handlers.RequireAuth(db), handlers.UploadFile(db))
	r.GET("/api/v1/uploads/:id", handlers.ServeFile(db))
	r.DELETE("/api/v1/attachments/:id", handlers.RequireSignatureVerification(), handlers.RequireAuth(db), handlers.DeleteAttachment(db))

	workspace := r.Group("/api/v1/workspace")
	workspace.Use(handlers.RequireSignatureVerification(), handlers.RequireAuth(db))
	{
		workspace.GET("/stats", handlers.WorkspaceStats(db))
		workspace.GET("/files", handlers.ListWorkspaceFiles(db))
		workspace.GET("/files/*path", handlers.ReadWorkspaceFile(db))
		workspace.POST("/upload", handlers.UploadTextFile(db))
		workspace.POST("/batch-upload", handlers.BatchUploadTextFiles(db))
		workspace.DELETE("/files/*path", handlers.DeleteWorkspaceFile(db))
	}

	r.GET("/ws", handlers.WebSocketHandler(db))
}

func setupStaticRoutes(r *gin.Engine, webDir string, embeddedWeb embed.FS) {
	mimeTypes := map[string]string{
		".js":    "application/javascript",
		".css":   "text/css",
		".html":  "text/html",
		".json":  "application/json",
		".png":   "image/png",
		".jpg":   "image/jpeg",
		".svg":   "image/svg+xml",
		".ico":   "image/x-icon",
		".woff":  "font/woff",
		".woff2": "font/woff2",
	}

	getMimeType := func(path string) string {
		ext := ""
		if i := strings.LastIndex(path, "."); i > 0 {
			ext = path[i:]
		}
		if mime, ok := mimeTypes[ext]; ok {
			return mime
		}
		return "application/octet-stream"
	}

	validExts := map[string]bool{
		".js": true, ".css": true, ".png": true, ".jpg": true, ".jpeg": true,
		".svg": true, ".ico": true, ".woff": true, ".woff2": true, ".ttf": true,
		".eot": true, ".otf": true, ".webp": true, ".gif": true, ".webm": true,
		".mp4": true, ".wav": true, ".mp3": true,
	}

	isValidAsset := func(ext string) bool {
		return validExts[ext]
	}

	if webDir == "" {
		subFS, err := fs.Sub(embeddedWeb, "web")
		if err != nil {
			log.Fatal("Failed to access embedded web filesystem:", err)
		}

		r.GET("/", func(c *gin.Context) {
			f, err := subFS.Open("index.html")
			if err != nil {
				c.String(404, "index.html not found")
				return
			}
			defer f.Close()
			c.Header("Cache-Control", "no-cache")
			c.Header("Content-Type", "text/html; charset=utf-8")
			if _, err := io.Copy(c.Writer, f); err != nil {
				c.String(500, "Failed to serve file")
			}
		})

		r.GET("/assets/*path", func(c *gin.Context) {
			path := strings.TrimPrefix(c.Param("path"), "/")
			ext := ""
			if i := strings.LastIndex(path, "."); i > 0 {
				ext = path[i:]
			}
			if !isValidAsset(ext) {
				c.JSON(404, gin.H{"error": "Not found"})
				return
			}
			f, err := subFS.Open("assets/" + path)
			if err != nil {
				c.String(404, "file not found")
				return
			}
			defer f.Close()
			c.Header("Content-Type", getMimeType(path))
			if _, err := io.Copy(c.Writer, f); err != nil {
				c.String(500, "Failed to serve file")
			}
		})

		r.NoRoute(func(c *gin.Context) {
			path := c.Request.URL.Path
			if strings.HasPrefix(path, "/api/") || strings.HasPrefix(path, "/ws") {
				c.JSON(404, gin.H{"error": "Not found"})
				return
			}
			f, err := subFS.Open("index.html")
			if err != nil {
				c.String(404, "index.html not found")
				return
			}
			defer f.Close()
			c.Status(200)
			c.Header("Cache-Control", "no-cache")
			c.Header("Content-Type", "text/html; charset=utf-8")
			if _, err := io.Copy(c.Writer, f); err != nil {
				c.String(500, "Failed to serve file")
			}
		})
	} else {
		r.GET("/", func(c *gin.Context) {
			c.File(webDir + "/index.html")
		})

		r.GET("/assets/*path", func(c *gin.Context) {
			path := c.Param("path")
			ext := ""
			if i := strings.LastIndex(path, "."); i > 0 {
				ext = path[i:]
			}
			if !isValidAsset(ext) {
				c.JSON(404, gin.H{"error": "Not found"})
				return
			}
			c.File(webDir + "/assets/" + path)
		})

		r.NoRoute(func(c *gin.Context) {
			path := c.Request.URL.Path
			if strings.HasPrefix(path, "/api/") || strings.HasPrefix(path, "/ws") {
				c.JSON(404, gin.H{"error": "Not found"})
				return
			}
			c.File(webDir + "/index.html")
		})
	}
}

func main() {
	// CLI commands
	resetPasswordCmd := flag.NewFlagSet("reset-password", flag.ExitOnError)
	userNickname := resetPasswordCmd.String("user", "", "User nickname")
	newPassword := resetPasswordCmd.String("password", "", "New password")

	resetSystemCmd := flag.NewFlagSet("reset-system", flag.ExitOnError)
	resetSystemYes := resetSystemCmd.Bool("yes", false, "Skip the interactive confirmation prompt")

	configFilePath := flag.String("config", "", "Path to config file (reads env vars from file)")

	// If a subcommand is present, route to its handler before any long-running
	// setup (config load, DB init, HTTP server) so reset / help never start a
	// server. The subcommand can also receive `-config` to know which DB to
	// connect to.
	if subcommand, _ := detectSubcommand(os.Args[1:]); subcommand != "" {
		// Compute subArgs from the post-flag-removal slice so indices stay
		// accurate when `-config` is stripped out.
		fullArgs := append([]string{}, os.Args[1:]...)
		if v, ok := extractFlag(fullArgs, "config"); ok {
			*configFilePath = v
			fullArgs = removeFlag(fullArgs, "config")
		}
		if *configFilePath != "" {
			log.Printf("Loading config from: %s", *configFilePath)
			if err := loadEnvFromFile(*configFilePath); err != nil {
				log.Fatalf("Failed to load config file: %v", err)
			}
		} else if autoConfigPath := autoDetectConfig(); autoConfigPath != "" {
			log.Printf("Auto-loading config from: %s", autoConfigPath)
			if err := loadEnvFromFile(autoConfigPath); err != nil {
				log.Fatalf("Failed to load auto-detected config file: %v", err)
			}
		}
		// Drop the subcommand itself; the remaining args (before + after)
		// are what the subcommand's FlagSet should see.
		idx := indexOf(fullArgs, subcommand)
		var subArgs []string
		if idx > 0 {
			subArgs = append(subArgs, fullArgs[:idx]...)
		}
		if idx+1 < len(fullArgs) {
			subArgs = append(subArgs, fullArgs[idx+1:]...)
		}
		switch subcommand {
		case "reset-password":
			resetPasswordCmd.Parse(subArgs)
			if *userNickname == "" || *newPassword == "" {
				fmt.Println("Usage: kanban-server reset-password -user <nickname> -password <newpassword>")
				os.Exit(1)
			}
			runPasswordReset(*userNickname, *newPassword)
			return
		case "reset-system":
			resetSystemCmd.Parse(subArgs)
			runSystemReset(*resetSystemYes)
			return
		case "help", "--help":
			printUsage()
			return
		}
	}

	flag.Parse()

	if *configFilePath != "" {
		log.Printf("Loading config from: %s", *configFilePath)
		if err := loadEnvFromFile(*configFilePath); err != nil {
			log.Fatalf("Failed to load config file: %v", err)
		}
	} else if autoConfigPath := autoDetectConfig(); autoConfigPath != "" {
		log.Printf("Auto-loading config from: %s", autoConfigPath)
		if err := loadEnvFromFile(autoConfigPath); err != nil {
			log.Fatalf("Failed to load auto-detected config file: %v", err)
		}
	}

	// Initialize config
	config.InitConfig()

	// First-run / lazy-setup: if the binary is the MySQL-only build and no
	// DB credentials are configured, skip the eager database.InitDB() call
	// here. The HTTP server will still come up, register only the setup
	// routes (Init / InitDefaults / Avatars), and let the setup wizard
	// supply DB credentials via the Advanced block. The Init handler then
	// bootstraps the connection itself, writes kanban.env, and triggers a
	// self-restart so the next startup loads the persisted config normally.
	var db *sql.DB
	if mysqlNeedsLazySetup() {
		log.Println("=================================================================")
		log.Println(" No MySQL connection details found in the environment.")
		log.Println(" Starting in setup mode. Open this server's URL in a browser to")
		log.Println(" complete the setup wizard and provide database credentials.")
		log.Println("=================================================================")
	} else {
		var err error
		db, err = database.InitDB()
		if err != nil {
			log.Fatal("Failed to initialize database:", err)
		}
	}

	// Initialize webhook service
	services.InitWebhookService()

	// Create Gin router
	r := gin.New()

	// Structured logging middleware
	r.Use(handlers.RequestLoggerMiddleware())

	// Global rate limiting middleware
	r.Use(handlers.GlobalRateLimitMiddleware())

	// Compression middleware for API responses
	r.Use(handlers.CompressionMiddleware())

	// CORS middleware
	r.Use(corsMiddleware())

	// Health check endpoint (public, no auth required)
	r.GET("/api/v1/health", handlers.HealthCheck)
	r.GET("/api/v1/status", handlers.HealthCheck)

	// Setup API routes. The init endpoint can request a self-restart once the
	// setup wizard finishes writing kanban.env, so we forward a callback that
	// signals the HTTP server to shut down and spawn a replacement process.
	restartCh := make(chan string, 1)
	onConfigPersisted := func(path string) {
		select {
		case restartCh <- path:
		default:
		}
	}
	if db == nil {
		// First-run / lazy-setup: only the endpoints required by the setup
		// wizard are reachable. Everything else (login, boards, tasks, …)
		// requires a connected DB and will return 404 until the wizard
		// completes and the process restarts with the persisted config.
		setupOnlyRoutes(r, onConfigPersisted)
	} else {
		setupAPIRoutes(r, db, onConfigPersisted)
	}

	// Static files - serve embedded frontend by default, or from WEB_DIR if set
	webDir := os.Getenv("WEB_DIR")

	if webDir != "" {
		if _, err := os.Stat(webDir); err != nil {
			log.Printf("Warning: Web directory not found at %s, falling back to embedded web", webDir)
			webDir = ""
		}
	}

	useEmbedded := webDir == ""
	if useEmbedded {
		log.Println("Serving embedded web assets")
	} else {
		log.Printf("Serving static files from: %s", webDir)
	}

	setupStaticRoutes(r, webDir, embeddedWeb)

	// Get port from env
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	// Print startup banner
	fmt.Println("")
	fmt.Println(`   dP"Yb  88""Yb 888888 88b 88     88  dP    db    88b 88 88""Yb    db    88b 88 `)
	fmt.Println(`  dP   Yb 88__dP 88__   88Yb88     88odP    dPYb   88Yb88 88__dP   dPYb   88Yb88 `)
	fmt.Println(`  Yb   dP 88"""  88""   88 Y88     88"Yb   dP__Yb  88 Y88 88""Yb  dP__Yb  88 Y88 `)
	fmt.Println(`   YbodP  88     888888 88  Y8     88  Yb dP""""Yb 88  Y8 88oodP dP""""Yb 88  Y8 `)
	fmt.Println("")
	fmt.Println("  https://github.com/songkl/open-kanban")
	fmt.Println("")
	fmt.Println("")
	log.Printf("Server starting on port %s", port)

	httpServer := &http.Server{
		Addr:    ":" + port,
		Handler: r,
	}

	// Wire graceful shutdown so the self-restart path can stop accepting
	// connections cleanly before the replacement process binds the port.
	shutdownSignal := make(chan os.Signal, 1)
	signal.Notify(shutdownSignal, syscall.SIGINT, syscall.SIGTERM)
	shutdownHTTP := func(reason string) {
		log.Printf("Shutting down HTTP server (%s)...", reason)
		shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		if err := httpServer.Shutdown(shutdownCtx); err != nil {
			log.Printf("HTTP server shutdown error: %v", err)
		}
	}
	go func() {
		select {
		case <-shutdownSignal:
			shutdownHTTP("signal received")
		case path := <-restartCh:
			TriggerSelfRestart(fmt.Sprintf("config written to %s by setup wizard", path))
			shutdownHTTP("self-restart requested")
		}
	}()

	if err := httpServer.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		log.Fatal("Failed to start server:", err)
	}
	log.Println("HTTP server stopped")
}

func printUsage() {
	fmt.Println("kanban-server - Open Kanban Server")
	fmt.Println("")
	fmt.Println("Usage:")
	fmt.Println("  kanban-server [options]")
	fmt.Println("  kanban-server reset-password -user <nickname> -password <newpassword>")
	fmt.Println("  kanban-server reset-system [-yes]")
	fmt.Println("")
	fmt.Println("Options:")
	fmt.Println("  -config <path>   Path to config file (reads env vars from file)")
	fmt.Println("")
	fmt.Println("Examples:")
	fmt.Println("  kanban-server -config /tmp/kanban.env")
	fmt.Println("  kanban-server -config /etc/kanban.env")
	fmt.Println("  kanban-server reset-system -yes")
	fmt.Println("")
}

func runPasswordReset(nickname, newPassword string) {
	db, err := database.InitDB()
	if err != nil {
		log.Fatal("Failed to initialize database:", err)
	}
	defer db.Close()

	// Hash password with salt
	hashedPassword, err := handlers.HashPasswordWithSalt(newPassword)
	if err != nil {
		log.Fatal("Failed to hash password:", err)
	}

	result, err := db.Exec("UPDATE users SET password = ?, updated_at = datetime('now') WHERE nickname = ?", hashedPassword, nickname)
	if err != nil {
		log.Fatal("Failed to update password:", err)
	}

	rowsAffected, _ := result.RowsAffected()
	if rowsAffected == 0 {
		log.Fatal("User not found: ", nickname)
	}

	fmt.Printf("Password reset successfully for user: %s\n", nickname)
}

// runSystemReset wipes all user accounts and tokens so the setup wizard can
// be re-run from scratch. FK constraints cascade so dependent rows in
// board_permissions / activities / column_permissions / tokens go away
// with the users. App config is cleared so the next init starts from
// defaults (allowRegistration=true, requirePassword=password-present,
// authEnabled=true).
func runSystemReset(skipConfirm bool) {
	if !skipConfirm {
		fmt.Println("This will DELETE ALL users, tokens, and app config.")
		fmt.Println("After this completes, the setup wizard will re-create the first admin user.")
		fmt.Print("Type 'yes' to continue: ")
		var input string
		_, _ = fmt.Scanln(&input)
		if input != "yes" {
			fmt.Println("Aborted.")
			return
		}
	}

	db, err := database.InitDB()
	if err != nil {
		log.Fatal("Failed to connect to database: ", err)
	}
	defer db.Close()

	tables := []string{
		"tokens",
		"app_config",
		"users",
	}
	for _, table := range tables {
		if _, err := db.Exec(fmt.Sprintf("DELETE FROM %s", table)); err != nil {
			log.Fatalf("Failed to clear %s: %v", table, err)
		}
	}

	fmt.Println("System reset complete. Restart the server (or refresh /setup) to create a new admin user.")
}
